//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDK.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MDK Projects.
        /// </summary>
        internal static string BlueprintManagerCommand_OnExecute_NoMDKProjects {
            get {
                return ResourceManager.GetString("BlueprintManagerCommand_OnExecute_NoMDKProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid MDK projects in this solution..
        /// </summary>
        internal static string BlueprintManagerCommand_OnExecute_NoMDKProjectsDescription {
            get {
                return ResourceManager.GetString("BlueprintManagerCommand_OnExecute_NoMDKProjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the blueprint {0}?.
        /// </summary>
        internal static string BlueprintManagerDialog_OnDeletingBlueprint_Description {
            get {
                return ResourceManager.GetString("BlueprintManagerDialog_OnDeletingBlueprint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Blueprint.
        /// </summary>
        internal static string BlueprintManagerDialog_OnDeletingBlueprint_Title {
            get {
                return ResourceManager.GetString("BlueprintManagerDialog_OnDeletingBlueprint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deleting Blueprint.
        /// </summary>
        internal static string BlueprintManagerDialogModel_Delete_Error {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to delete the blueprint.
        ///
        ///{0}.
        /// </summary>
        internal static string BlueprintManagerDialogModel_Delete_Error_Description {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_Delete_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t Delete Blueprint.
        /// </summary>
        internal static string BlueprintModel_Delete_Error {
            get {
                return ResourceManager.GetString("BlueprintModel_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blueprint {0} could not be deleted:
        ///
        ///{1}.
        /// </summary>
        internal static string BlueprintModel_Error_Description {
            get {
                return ResourceManager.GetString("BlueprintModel_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty or contain any of the following characters: {0}.
        /// </summary>
        internal static string BlueprintModel_GetErrors_InvalidName {
            get {
                return ResourceManager.GetString("BlueprintModel_GetErrors_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Find Space Engineers.
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalBinPath_SEBinPathNotFound {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalBinPath_SEBinPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the install path of Space Engineers. Please install the game before creating an Ingame Script project..
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalBinPath_SEBinPathNotFoundDescription {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalBinPath_SEBinPathNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the MDK/SE install path. The install might be corrupted. Please reinstall the extension..
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalInstallPath_CannotFindMDKPathDescription {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalInstallPath_CannotFindMDKPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Find MDK Utility Path.
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalInstallPath_CannotMDKPath {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalInstallPath_CannotMDKPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Create Folder.
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalOutputPath_CannotCreateOutputPath {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalOutputPath_CannotCreateOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the desired output path.
        ///{0}.
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalOutputPath_CannotCreateOutputPathDescription {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalOutputPath_CannotCreateOutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Find MDK Settings.
        /// </summary>
        internal static string IngameScriptWizard_TryGetProperties_MDKSettingsNotFound {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetProperties_MDKSettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the MDK/SE settings. The install might be corrupted. Please reinstall the extension..
        /// </summary>
        internal static string IngameScriptWizard_TryGetProperties_MDKSettingsNotFoundDescription {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetProperties_MDKSettingsNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build failed. Please make sure your script compiles properly before attempting deployment..
        /// </summary>
        internal static string MDKPackage_Deploy_BuildFailed {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying All MDK Scripts....
        /// </summary>
        internal static string MDKPackage_Deploy_DeployingAllScripts {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeployingAllScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying MDK Script {0}....
        /// </summary>
        internal static string MDKPackage_Deploy_DeployingSingleScript {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeployingSingleScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Cancelled.
        /// </summary>
        internal static string MDKPackage_Deploy_DeploymentCancelled {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeploymentCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Complete.
        /// </summary>
        internal static string MDKPackage_Deploy_DeploymentComplete {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeploymentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your script(s) should now be available in the ingame local workshop..
        /// </summary>
        internal static string MDKPackage_Deploy_DeploymentCompleteDescription {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeploymentCompleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Failed.
        /// </summary>
        internal static string MDKPackage_Deploy_DeploymentFailed {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeploymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Rejected.
        /// </summary>
        internal static string MDKPackage_Deploy_DeploymentRejected {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeploymentRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The emphasized blueprints are the ones that were just deployed..
        /// </summary>
        internal static string MDKPackage_Deploy_Description {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no deployable scripts in this solution..
        /// </summary>
        internal static string MDKPackage_Deploy_NoMDKProjects {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_NoMDKProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No solution is open..
        /// </summary>
        internal static string MDKPackage_Deploy_NoSolutionOpen {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_NoSolutionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A build is currently in progress. Please try again when the current build is complete..
        /// </summary>
        internal static string MDKPackage_Deploy_Rejected_BuildInProgress {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_Rejected_BuildInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deployment is currently in progress. Please try again when the current deployment is complete..
        /// </summary>
        internal static string MDKPackage_Deploy_Rejected_DeploymentInProgress {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_Rejected_DeploymentInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to deploy..
        /// </summary>
        internal static string MDKPackage_Deploy_UnexpectedError {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MDK Projects.
        /// </summary>
        internal static string ProjectOptionsCommand_OnExecute_NoMDKProjects {
            get {
                return ResourceManager.GetString("ProjectOptionsCommand_OnExecute_NoMDKProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid MDK projects in this solution..
        /// </summary>
        internal static string ProjectOptionsCommand_OnExecute_NoMDKProjectsDescription {
            get {
                return ResourceManager.GetString("ProjectOptionsCommand_OnExecute_NoMDKProjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Failed.
        /// </summary>
        internal static string RequestUpgradeDialogModel_OnSave_Error {
            get {
                return ResourceManager.GetString("RequestUpgradeDialogModel_OnSave_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to upgrade the project(s)..
        /// </summary>
        internal static string RequestUpgradeDialogModel_OnSave_Error_Description {
            get {
                return ResourceManager.GetString("RequestUpgradeDialogModel_OnSave_Error_Description", resourceCulture);
            }
        }
    }
}
