//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDK.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MDK Projects.
        /// </summary>
        internal static string BlueprintManagerCommand_OnExecute_NoMDKProjects {
            get {
                return ResourceManager.GetString("BlueprintManagerCommand_OnExecute_NoMDKProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid MDK projects in this solution..
        /// </summary>
        internal static string BlueprintManagerCommand_OnExecute_NoMDKProjectsDescription {
            get {
                return ResourceManager.GetString("BlueprintManagerCommand_OnExecute_NoMDKProjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the script {0}?.
        /// </summary>
        internal static string BlueprintManagerDialog_OnDeletingBlueprint_Description {
            get {
                return ResourceManager.GetString("BlueprintManagerDialog_OnDeletingBlueprint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Script.
        /// </summary>
        internal static string BlueprintManagerDialog_OnDeletingBlueprint_Title {
            get {
                return ResourceManager.GetString("BlueprintManagerDialog_OnDeletingBlueprint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string BlueprintManagerDialogModel_CopyToClipboard_Copy {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_CopyToClipboard_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The script was copied to the clipboard..
        /// </summary>
        internal static string BlueprintManagerDialogModel_CopyToClipboard_Copy_Description {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_CopyToClipboard_Copy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Copying Script.
        /// </summary>
        internal static string BlueprintManagerDialogModel_CopyToClipboard_Copy_Error {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_CopyToClipboard_Copy_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to copy the script.
        ///
        ///{0}.
        /// </summary>
        internal static string BlueprintManagerDialogModel_CopyToClipboard_Copy_Error_Description {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_CopyToClipboard_Copy_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deleting Script.
        /// </summary>
        internal static string BlueprintManagerDialogModel_Delete_Error {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to delete the script.
        ///
        ///{0}.
        /// </summary>
        internal static string BlueprintManagerDialogModel_Delete_Error_Description {
            get {
                return ResourceManager.GetString("BlueprintManagerDialogModel_Delete_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t Delete Script.
        /// </summary>
        internal static string BlueprintModel_Delete_Error {
            get {
                return ResourceManager.GetString("BlueprintModel_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The script {0} could not be deleted:
        ///
        ///{1}.
        /// </summary>
        internal static string BlueprintModel_Error_Description {
            get {
                return ResourceManager.GetString("BlueprintModel_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty or contain any of the following characters: {0}.
        /// </summary>
        internal static string BlueprintModel_GetErrors_InvalidName {
            get {
                return ResourceManager.GetString("BlueprintModel_GetErrors_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating the combined script for {0}.
        /// </summary>
        internal static string BuildModule_CreateProgramDocument_Error {
            get {
                return ResourceManager.GetString("BuildModule_CreateProgramDocument_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating script for {0}.
        /// </summary>
        internal static string BuildModule_GenerateScript_ErrorGeneratingScript {
            get {
                return ResourceManager.GetString("BuildModule_GenerateScript_ErrorGeneratingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading configuration for {0}.
        /// </summary>
        internal static string BuildModule_LoadConfig_Error {
            get {
                return ResourceManager.GetString("BuildModule_LoadConfig_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading the content for {0}.
        /// </summary>
        internal static string BuildModule_LoadContent_Error {
            get {
                return ResourceManager.GetString("BuildModule_LoadContent_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading script projects from {0}.
        /// </summary>
        internal static string BuildModule_LoadScriptProjects_Error {
            get {
                return ResourceManager.GetString("BuildModule_LoadScriptProjects_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error minifying {0} (stage 2).
        /// </summary>
        internal static string BuildModule_PostMinify_Error {
            get {
                return ResourceManager.GetString("BuildModule_PostMinify_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error minifying {0} (stage 1).
        /// </summary>
        internal static string BuildModule_PreMinify_Error {
            get {
                return ResourceManager.GetString("BuildModule_PreMinify_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing final script for {0}.
        /// </summary>
        internal static string BuildModule_WriteScript_Error {
            get {
                return ResourceManager.GetString("BuildModule_WriteScript_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDK was not allowed to write the final script for {0}: Unauthorized access.
        /// </summary>
        internal static string BuildModule_WriteScript_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("BuildModule_WriteScript_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Write Whitelist Cache.
        /// </summary>
        internal static string IngameScriptWizard_ProjectItemFinishedGenerating_CannotWriteWhitelistCache {
            get {
                return ResourceManager.GetString("IngameScriptWizard_ProjectItemFinishedGenerating_CannotWriteWhitelistCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to write the whitelist cache.
        ///
        ///{0}.
        /// </summary>
        internal static string IngameScriptWizard_ProjectItemFinishedGenerating_CannotWriteWhitelistCacheDescription {
            get {
                return ResourceManager.GetString("IngameScriptWizard_ProjectItemFinishedGenerating_CannotWriteWhitelistCacheDescrip" +
                        "tion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Find Space Engineers.
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalBinPath_SEBinPathNotFound {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalBinPath_SEBinPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the install path of Space Engineers. Please install the game before creating an Ingame Script project..
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalBinPath_SEBinPathNotFoundDescription {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalBinPath_SEBinPathNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the MDK/SE install path. The install might be corrupted. Please reinstall the extension..
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalInstallPath_CannotFindMDKPathDescription {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalInstallPath_CannotFindMDKPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Find MDK Utility Path.
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalInstallPath_CannotMDKPath {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalInstallPath_CannotMDKPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Create Folder.
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalOutputPath_CannotCreateOutputPath {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalOutputPath_CannotCreateOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the desired output path.
        ///{0}.
        /// </summary>
        internal static string IngameScriptWizard_TryGetFinalOutputPath_CannotCreateOutputPathDescription {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetFinalOutputPath_CannotCreateOutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Find MDK Settings.
        /// </summary>
        internal static string IngameScriptWizard_TryGetProperties_MDKSettingsNotFound {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetProperties_MDKSettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the MDK/SE settings. Make sure your Visual Studio is up to date. If this does not work, the install might be corrupted and might need reinstalling..
        /// </summary>
        internal static string IngameScriptWizard_TryGetProperties_MDKSettingsNotFoundDescription {
            get {
                return ResourceManager.GetString("IngameScriptWizard_TryGetProperties_MDKSettingsNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build failed. Please make sure your script compiles properly before attempting deployment..
        /// </summary>
        internal static string MDKPackage_Deploy_BuildFailed {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying All MDK Scripts....
        /// </summary>
        internal static string MDKPackage_Deploy_DeployingAllScripts {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeployingAllScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying MDK Script {0}....
        /// </summary>
        internal static string MDKPackage_Deploy_DeployingSingleScript {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeployingSingleScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Cancelled.
        /// </summary>
        internal static string MDKPackage_Deploy_DeploymentCancelled {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeploymentCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Complete.
        /// </summary>
        internal static string MDKPackage_Deploy_DeploymentComplete {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeploymentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your script(s) should now be available in the ingame local workshop..
        /// </summary>
        internal static string MDKPackage_Deploy_DeploymentCompleteDescription {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeploymentCompleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Failed.
        /// </summary>
        internal static string MDKPackage_Deploy_DeploymentFailed {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeploymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Rejected.
        /// </summary>
        internal static string MDKPackage_Deploy_DeploymentRejected {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_DeploymentRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The emphasized scripts are the ones that were just deployed..
        /// </summary>
        internal static string MDKPackage_Deploy_Description {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no deployable scripts in this solution..
        /// </summary>
        internal static string MDKPackage_Deploy_NoMDKProjects {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_NoMDKProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No solution is open..
        /// </summary>
        internal static string MDKPackage_Deploy_NoSolutionOpen {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_NoSolutionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A build is currently in progress. Please try again when the current build is complete..
        /// </summary>
        internal static string MDKPackage_Deploy_Rejected_BuildInProgress {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_Rejected_BuildInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deployment is currently in progress. Please try again when the current deployment is complete..
        /// </summary>
        internal static string MDKPackage_Deploy_Rejected_DeploymentInProgress {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_Rejected_DeploymentInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy exceeds in-game script character limit of 100,000 characters. Your script has a length of {0:N0} characters..
        /// </summary>
        internal static string MDKPackage_Deploy_Too_Long_Warning {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_Too_Long_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to deploy..
        /// </summary>
        internal static string MDKPackage_Deploy_UnexpectedError {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Warning.
        /// </summary>
        internal static string MDKPackage_Deploy_Warning_Title {
            get {
                return ResourceManager.GetString("MDKPackage_Deploy_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Analyzing Project.
        /// </summary>
        internal static string MDKPackage_OnProjectLoaded_ErrorAnalyzingProject {
            get {
                return ResourceManager.GetString("MDKPackage_OnProjectLoaded_ErrorAnalyzingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to analyze the project {0}. MDK has been disabled to prevent further crashes..
        /// </summary>
        internal static string MDKPackage_OnProjectLoaded_ErrorAnalyzingProject_Description {
            get {
                return ResourceManager.GetString("MDKPackage_OnProjectLoaded_ErrorAnalyzingProject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Analyzing Solution.
        /// </summary>
        internal static string MDKPackage_OnSolutionLoaded_ErrorAnalyzingSolution {
            get {
                return ResourceManager.GetString("MDKPackage_OnSolutionLoaded_ErrorAnalyzingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to analyze the solution. MDK has been disabled to prevent further crashes..
        /// </summary>
        internal static string MDKPackage_OnSolutionLoaded_ErrorAnalyzingSolution_Description {
            get {
                return ResourceManager.GetString("MDKPackage_OnSolutionLoaded_ErrorAnalyzingSolution_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game binaries are required to create and deploy an MDK project..
        /// </summary>
        internal static string NewScriptWizardDialogModel_GameBinPath_GameBinariesRequired {
            get {
                return ResourceManager.GetString("NewScriptWizardDialogModel_GameBinPath_GameBinariesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output path is required to create an MDK project..
        /// </summary>
        internal static string NewScriptWizardDialogModel_OutputPath_OutputPathRequired {
            get {
                return ResourceManager.GetString("NewScriptWizardDialogModel_OutputPath_OutputPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups have been stored in the projects&apos; parent folders..
        /// </summary>
        internal static string ProjectHealthDialog_OnUpgradeCompleted_BackupsStoredMessage {
            get {
                return ResourceManager.GetString("ProjectHealthDialog_OnUpgradeCompleted_BackupsStoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following MDK projects must be upgraded in order to function correctly. Do you wish to do this now?.
        /// </summary>
        internal static string ProjectHealthDialogModel_DefaultMessage {
            get {
                return ResourceManager.GetString("ProjectHealthDialogModel_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Failed.
        /// </summary>
        internal static string ProjectHealthDialogModel_OnSave_Error {
            get {
                return ResourceManager.GetString("ProjectHealthDialogModel_OnSave_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the attempt to upgrade the project(s)..
        /// </summary>
        internal static string ProjectHealthDialogModel_OnSave_Error_Description {
            get {
                return ResourceManager.GetString("ProjectHealthDialogModel_OnSave_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upgrade process has been completed. It is recommended to restart Visual Studio in order to reload the extensions and analyzers..
        /// </summary>
        internal static string ProjectHealthDialogModel_RunUpgrades_Description {
            get {
                return ResourceManager.GetString("ProjectHealthDialogModel_RunUpgrades_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Complete.
        /// </summary>
        internal static string ProjectHealthDialogModel_RunUpgrades_UpgradeComplete {
            get {
                return ResourceManager.GetString("ProjectHealthDialogModel_RunUpgrades_UpgradeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Options File - was tagged as outdated, but can&apos;t find the right upgrade tool for version {0}.
        /// </summary>
        internal static string ProjectHealthDialogModel_Upgrade_BadUpgradeVersion {
            get {
                return ResourceManager.GetString("ProjectHealthDialogModel_Upgrade_BadUpgradeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MDK Projects.
        /// </summary>
        internal static string ProjectOptionsCommand_OnExecute_NoMDKProjects {
            get {
                return ResourceManager.GetString("ProjectOptionsCommand_OnExecute_NoMDKProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid MDK projects in this solution..
        /// </summary>
        internal static string ProjectOptionsCommand_OnExecute_NoMDKProjectsDescription {
            get {
                return ResourceManager.GetString("ProjectOptionsCommand_OnExecute_NoMDKProjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whitelist caches have been updated. You might need to rebuild your project for any changes to take effect..
        /// </summary>
        internal static string RefreshWhitelistCacheCommand_OnExecute_UpdatedWhitelistsDescription {
            get {
                return ResourceManager.GetString("RefreshWhitelistCacheCommand_OnExecute_UpdatedWhitelistsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitelist Caches Updated.
        /// </summary>
        internal static string RefreshWhitelistCacheCommand_OnExecute_UpdatedWhitelistsTitle {
            get {
                return ResourceManager.GetString("RefreshWhitelistCacheCommand_OnExecute_UpdatedWhitelistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Program entry point for {0}.
        /// </summary>
        internal static string TypeTrimmer_ProcessAsync_NoEntryPoint {
            get {
                return ResourceManager.GetString("TypeTrimmer_ProcessAsync_NoEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading the original project file.
        /// </summary>
        internal static string UpgradeFrom1_1_Upgrade_ErrorLoadingProject {
            get {
                return ResourceManager.GetString("UpgradeFrom1_1_Upgrade_ErrorLoadingProject", resourceCulture);
            }
        }
    }
}
